# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.


#model directory name ### Change before every new model run
model_name: trans_hflip_col_syd_fish_s2
#trans_hflip_col_syd_incBad ################# extra photos added from sydney dataset
#trans_flip_rot10_norm


# environment/computational parameters

 # random number generator seeds (long integer value) - turn each on/off for 3 replicate training runs.
#seed: 32678456782      
seed: 4436689132 #seed 2
#seed: 3945074475 #seed 3

device: cuda
num_workers: 4 #default is 4 - can try more for large file sizes

# dataset parameters ##################

# change to the location of data (image files)
data_root: Images\Test_17_23_medium\
#Images\Test_17_23_medium\ #images downloaded from iNat for test deployment of model
#syd_images_small\ # contains iNat + Syd images can be used for all models as label file controls which images are used

#syd_images_small\
#/mnt/ssd-cluster/chris/Images 
num_classes: 2                  # change to the number of classification classes
###Need to also update line 56 of train.py if adding classes


# test/train file names
train_label_file:  output\train_21_23_syd_fish_fix.csv #including extra sydney images
#train_21_23_syd_fish_fix.csv
#output\train_21_23_incBad_2cat.csv # iNat training image only
#output\train_21_23_syd_incBad_fix.csv #including extra sydney images
#output\SG_trans_hflip_col_syd_train.csv #seagrass + syd images training file

# output\SG_trans_hflip_col_train.csv #seagrass training file

###/mnt/ssd-cluster/chris/train_21_23_exBad.csv

val_label_file: Output\iNat_obs_17_23_testset_img_list.csv

# output\SG_trans_hflip_col_val.csv #seagrass validation label file
#output\val_incomplete_incBad_2cat.csv #validation_label_file  ###/mnt/ssd-cluster/chris/val_incomplete_exBad.csv
# Output\iNat_obs_17_23_testset_img_list.csv ###test_label_file - for deploying on 55k iNat photos

#original training file /mnt/ssd-cluster/chris/train_21_23_exBad.csv


# training hyperparameters
image_size: [224, 224]    ### Change this to change image sizes (need to be square)
num_epochs: 60  ### an epoch is a pass through the entire dataset
batch_size: 32   ### number of images processed at one 'time' #default was 32
learning_rate: 0.001
weight_decay: 0.001

#weighting
weighting: False

#transformation parameters (augmentations)
# transformations need to be turned on/off in dataset.py Lines 65-76
flip_prob: 0.5
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
#rotation_deg: [0, 0] #currently removed from dataloader
#blur_kern: [5, 9] #Gaussian Blur kernel size
#blur_sigma: [0.1, 5] #Gaussian Blur sigma

