# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.


#model directory name ### Change before every new model run
model_name: trans_hflip_col_syd_fish_s1

# environment/computational parameters

 # random number generator seeds (long integer value) - turn each on/off for 3 replicate training runs.
seed: 32678456782      
#seed: 4436689132 #seed 2
#seed: 3945074475 #seed 3

device: cuda
num_workers: 4 #default is 4 - can try more for large file sizes

# dataset parameters ##################

# change to the location of data (image files)
data_root: Images\


num_classes: 2                  # change to the number of classification classes
###Need to also update line 56 of train.py if adding classes


# test/train file names
train_label_file:  data\train.csv #including extra sydney images

val_label_file: data\val.csv #can also point to new images to deploy model

#e.g. deployment_test_list_55k 
# data\deployment_test_list_55k.csv ###test_label_file - for deploying on 55k iNat photos


# training hyperparameters
image_size: [224, 224]    ### Change this to change image sizes (need to be square)
num_epochs: 60  ### an epoch is a pass through the entire dataset
batch_size: 32   ### number of images processed at one 'time' #default was 32
learning_rate: 0.001
weight_decay: 0.001

#weighting
weighting: False

#transformation parameters (augmentations)
# transformations need to be turned on/off in dataset.py Lines 65-76
flip_prob: 0.5
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
#rotation_deg: [0, 0] #currently removed from dataloader
#blur_kern: [5, 9] #Gaussian Blur kernel size
#blur_sigma: [0.1, 5] #Gaussian Blur sigma

